title: 'Splunk n Stuff'
description: 'Fiddling with data!'
#show_downloads: false
baseurl: ''
paginate: 5
permalink: pretty
future: true
author:
  name: Fontora Vixol
  url: https://fontora.dev
  email: me@fontora.dev
plugins:
#  - jekyll-archives
  - jekyll-feed
  # https://github.com/jekyll/jekyll-paginate - Needed?
  - jekyll-paginate 
  # https://github.com/jekyll/jekyll-sitemap 
  - jekyll-sitemap  

## Custom ##
version: 0.0.2
google_analytics: G-4E5ZN229LP
