title: 'Splunk n Stuff'
#tagline: ''
description: 'Fiddling with data!'
#show_downloads: false
baseurl: ''
paginate: 5
permalink: pretty

author:
  name: Fontora Vixol
  url: https://fontora.dev
  email: me@fontora.dev

plugins:
#  - jekyll-archives
  - jekyll-feed
  # https://github.com/jekyll/jekyll-paginate - Needed?
  - jekyll-paginate 
  # https://github.com/jekyll/jekyll-sitemap 
  - jekyll-sitemap  

# Custom
version: 0.0.1
google_analytics_id: UA-175213666-1
