theme: jekyll-theme-midnight
title: "Fontora's Dev Area"
description: "Fiddling with things I don't understand"
google_analytics: UA-175213666-1
show_downloads: false
url: "https://fontora.dev"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
