# Setup
title: 'Splunk n Stuff'
tagline: 'A Jekyll theme'
description: 'Fiddling with data things!'
#show_downloads: false
baseurl: ''
paginate: 5
permalink: pretty

# About
author:
  name: Fontora Vixol
  url: https://fontora.dev
  email: me@fontora.dev

# Plugins
plugins:
#  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate  
  - jekyll-sitemap  

# Custom
version: 0.0.1
google_analytics_id: UA-175213666-1
